### ISSUE TITLE
node_modules for already installed plugin resets on installing a new plugin 

### ISSUE THREAD

**Issue by danial24** [oclif/plugin-plugins#70]
We developed a cli using oclif
[bluebasecli](https://github.com/BlueBaseJS/cli)

I have different plugins like @bluebase/cli-web, @bluebase/cli-expo and @bluebase/cli-storybook

**Problem:**
Let say I install a plugin and explored the location where it is installed and verified that the node_modules directory is there with all the packages installed.
Now when I add another plugin what happens is that, it deletes the packages installed for the plugin1. But the node_modules are there for the second plugin(i-e the latest plugin).
 

**Steps leading to the problem:**

Install the cli
Add a plugin 
```
yarn global add @bluebase/cli
bluebase plugins:add @bluebase/cli-web
```
Go to the installed location which is in my case is 
```
cd ~/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules
```

The packages for **cli-web** are installed in the above mentioned directory

Now Install another package
```
bluebase plugins:add @bluebase/cli-expo
```
go to the directory for expo like
```
cd ~/.local/share/@bluebase/cli/node_modules/@bluebase/cli-expo/node_modules
```

The packages for expo are there but if you go the directory where web is install which was:
cd ~/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules
There are no packages installed.
Installing cli-expo reset the packages installed for cli-web.

**Comment by jdxcode** [comment]
aren't the packages all in `~/.local/share/@bluebase/cli/node_modules`?

**Comment by danial24** [comment]
@jdxcode 
Yes it is but the point is that there were node_modules in 
~/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules/
before installing the other plugin which reset but the modules still exist in ~/.local/share/@bluebase/cli/node_modules/

Let say there is a package **style-loader** that is in 
~/.local/share/@bluebase/cli/node_modules/

but still the system searches in 
~/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules/

**Here is the error trace:**

```
bluebase web:start
@bluebase/cli/web info: 	🌏 Starting BlueBase on Web...	
@bluebase/cli/web info: 	👨‍💻 Compiling BlueBase's client bundle	
ℹ ｢serve｣: Subscribed to 'build-finished' event
ℹ ｢serve｣: Subscribed to 'compiler-error' event
(node:7560) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:7560) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
ℹ ｢hot｣: WebSocket Server Listening on 0.0.0.0:39985
ℹ ｢serve｣: Serving Static Content from: /
ℹ ｢serve｣: Project is running at http://0.0.0.0:1337
ℹ ｢serve｣: Server URI copied to clipboard
✖ ｢wdm｣: Error: Can't resolve '/home/danial/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules/style-loader' in '/home/danial/Documents/workspace/dedupingIssue/web'
    at doResolve (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/Resolver.js:180:19)
    at hook.callAsync (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/danial/.local/share/@bluebase/cli/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/danial/.local/share/@bluebase/cli/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/danial/.local/share/@bluebase/cli/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/home/danial/.local/share/@bluebase/cli/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at hook.callAsync (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/danial/.local/share/@bluebase/cli/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/danial/.local/share/@bluebase/cli/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/home/danial/.local/share/@bluebase/cli/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
✖ ｢wdm｣: resolve '/home/danial/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules/style-loader' in '/home/danial/Documents/workspace/dedupingIssue/web'
  using description file: /home/danial/Documents/workspace/dedupingIssue/web/package.json (relative path: .)
    using description file: /home/danial/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/package.json (relative path: ./node_modules/style-loader)
      no extension
        /home/danial/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules/style-loader doesn't exist
      .js
        /home/danial/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules/style-loader.js doesn't exist
      .json
        /home/danial/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules/style-loader.json doesn't exist
      as directory
        /home/danial/.local/share/@bluebase/cli/node_modules/@bluebase/cli-web/node_modules/style-loader doesn't exist

```

**Comment by jdxcode** [comment]
yes this is how yarn works. [Read this for more information](https://npm.github.io/how-npm-works-docs/npm3/how-npm3-works.html.

**Comment by RasPhilCo** [comment]
Cleaning up - if you think this issue is still valid, reopen it. Thanks!
